### ISSUE TITLE
Suggestion to be added: explain how we farm - proof-of-blockstake

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/www_threefold.io#1]
On the .io website I would like to see explained how the TFTs are farmed and what's the technology making TFT mining green: talk about proof-of-blockstake. 

As explained on the whitepaper: "The TF Chain has been built using our Rivine.io blockchain stack. It is a distributed, “proof-of-blockstake” blockchain. (...) ThreeFold farming is energy efficient due to its thin operating system and the proof-of-stake blockchain, both of which require little energy to operate. " I would also add Rob's comments "The proof of Blockstake is actually a proof of stake amongst proven validators, As such, it is a permissioned blockchain. The blockstake is the proof of being a validator. In this respect, it's actually a hybrid between Proof of stake and "proof of authority" , a terminology that did not exist when we created the proof of blockstake but that is gaining popularity for permissioned blockchains. 
There is the Rivine whitepaper: https://github.com/rivine/rivine/blob/master/doc/whitepaper.md although it could use some updates to reflect the added features."

**Comment by despiegk** [comment]
lets put this on wiki of tech, and call this proof-of-blockstake

**Comment by VonSub** [comment]
@nbabenko can you pick this up when you have some spare time?
