### ISSUE TITLE
Grid Page: Dedicated Roadmap

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold.io#103]
Display at the end of the grid page a roadmap in nova style.

Three main milestones:
1) Grid Capacity Generation
2) Grid Capacity Activation
3) Grid Capacity Usage

Do you need a .md with all the text?

**Comment by VonSub** [comment]
ready for your updates @andhartl

**Comment by VonSub** [comment]
@andhartl please check if this is correct.
@ehab-hassan please update to be 3 parts. (mobile view it is still 5 dots, and regular view the lines are broken)

**Comment by VonSub** [comment]
this can be closed right?

**Comment by andhartl** [comment]
good to go. erased text in line two under activation
