### ISSUE TITLE
Typo in page name change to stats.md

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#11]
And check that it doesn't break things!!

https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/tokens/states.md

**Comment by VonSub** [comment]
@danleighton what is the issue here?

**Comment by danleighton** [comment]
Stats. Not statEs

**Comment by danleighton** [comment]
Stats. Not statEs
