### ISSUE TITLE
Home Page: Roadmap seems to disappear off bottom of page when page made narrow.

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#112]
<img width="839" alt="screen shot 2018-09-06 at 15 21 47" src="https://user-images.githubusercontent.com/7113864/45163595-9bd8b600-b1e8-11e8-8d2d-4c367f7ac3b0.png">

**Comment by VonSub** [comment]
Needs a little margin.. looks strange like this indeed.

@ehab-hassan @samaradel
