### ISSUE TITLE
Grid Page: Business model is incomplete

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#114]
In this section, the TF Foundation revenue share is mentioned...but not that going to TF Tech or any Cp-op.

https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/grid/earn_tokens.md

**Comment by andhartl** [comment]
this content will be be moved to the grid wiki. of course updated to the latest rev split, etc.
