### ISSUE TITLE
Grid Page: Layout is weird when page is made smaller...

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#115]
<img width="772" alt="screen shot 2018-09-06 at 16 36 24" src="https://user-images.githubusercontent.com/7113864/45168411-1dcddc80-b1f3-11e8-9396-be57c124c25c.png">

https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/grid/earn_tokens.md

**Comment by VonSub** [comment]
this would be tablet view?
