### ISSUE TITLE
Team Page: Ad call to action for chapters

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold.io#117]
ad call to action below chapter list: click here if you want to found a chapter.

**Comment by andhartl** [comment]
remove become a farmer call to action and ad chapter call to action instead

**Comment by andhartl** [comment]
check with Olivia if we can use her email address to send chapter requests to

**Comment by juradoo** [comment]
> check with Olivia if we can use her email address to send chapter requests to

connect@tfambassador.com
