### ISSUE TITLE
Grid page: Add existing farmer video above farmer call to action

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold.io#129]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/18591016/45303566-600a5d00-b516-11e8-8db9-de55b9b359d9.png">

**Comment by VonSub** [comment]
let's add a second button to the CTA (a blue one) "See Farming Video" (link: https://www.youtube.com/watch?v=fucXM2L2cTA )
