### ISSUE TITLE
Partner page: Add Farming Cooperatives block  between ind farmers and corp farmers

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold.io#132]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/18591016/45348662-86300b80-b5af-11e8-823c-6d4cadfcc3b4.png">

**Comment by VonSub** [comment]
@samaradel  @ehab-hassan  take the part of buy tokens.

- needs room for image
- description
- URL

<img width="1532" alt="screen shot 2018-09-11 at 14 28 34" src="https://user-images.githubusercontent.com/29431263/45360179-116cc980-b5cf-11e8-993f-c4a25de8a2e0.png">
<img width="1277" alt="screen shot 2018-09-11 at 13 54 44" src="https://user-images.githubusercontent.com/29431263/45360180-116cc980-b5cf-11e8-97a2-85baf7e92d31.png">
