### ISSUE TITLE
Partner Page: need to add explainer text underneath Corporate Farmers, Software Partners and TFT listing

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold.io#133]
need to be able to add text like it can be done for individual farmers

<img width="502" alt="image" src="https://user-images.githubusercontent.com/18591016/45348935-44ec2b80-b5b0-11e8-81ff-90edcdf02e2b.png">

**Comment by VonSub** [comment]
Add a subheader + text part to it. 
<img width="658" alt="screen shot 2018-09-11 at 11 34 24" src="https://user-images.githubusercontent.com/29431263/45351578-cd6dca80-b5b6-11e8-844b-85f29a90c8ba.png">
