### ISSUE TITLE
Grid Page: Earn Tokens blocks width.

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#151]
Block 1 is wider than block 2. Please make same width.

<img width="1552" alt="screen shot 2018-09-13 at 10 53 36" src="https://user-images.githubusercontent.com/29431263/45478321-eb1c6a80-b743-11e8-924e-3c629dd0bff4.png">

**Comment by samaradel** [comment]
duplicated #149
