### ISSUE TITLE
Link not working: T&C's

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/www_threefold.io#169]
Directs to homepage in stead of T&C's

**Comment by sabrinasadik** [comment]
Who is creating this?

**Comment by VonSub** [comment]
We should have this done by a person with a legal background. We can see what we have for BT, this got checked by a lawyer, let's see what parts fit for TF

**Comment by VonSub** [comment]
T&Cs are yet to be created

**Comment by VonSub** [comment]
moved to right repo: https://github.com/threefoldfoundation/www_threefold.io_new/issues/17
