### ISSUE TITLE
Link not working: Privacy Statement

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/www_threefold.io#170]
Redirects to homepage instead of Privacy Statement

**Comment by sabrinasadik** [comment]
Who is creating this?

**Comment by despiegk** [comment]
GDPR, where are the docs, need to link to PDF

**Comment by VonSub** [comment]
No need for PDF.
This is a published G-doc which updates automatically. It does need some work but it's good for now.

https://docs.google.com/document/d/e/2PACX-1vS8EQcZlu0uRafLWKbOMP_K2W_QWxvxncEcR-UOfz_8pfrfsxPzxZkH_z30fq7QxSWAi0WRno50ME37/pub

**Comment by VonSub** [comment]
@weynandkuijpers I would add this to the NOW sprint as we will implement this in upcoming website release

**Comment by VonSub** [comment]
moved to correct repo:https://github.com/threefoldfoundation/www_threefold.io_new/issues/16
