### ISSUE TITLE
Update Egypt Team Bio's for:

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#189]
Bio's still mention GIG.

https://docs.grid.tf/threefold/data_team

- [x] Bishoy Mikhaiel
- [x] Reem Khamis
- [x] John Kheir
- [x] Dina Magdi
- [x] Ahmed Thabet
- [x] Ramez Saeed

**Comment by ramezsaeed** [comment]
Done, please review
https://docs.grid.tf/threefold/data_team/commit/78d622216bca1799df5a442d6393578bbb076409

**Comment by VonSub** [comment]
@ramezsaeed thanks for the quick work, reviewed and ok.

**Comment by john-kheir** [comment]
Done

**Comment by VonSub** [comment]
Looks good @john-kheir

**Comment by xmonader** [comment]
@VonSub updated.

**Comment by Dinaamagdy** [comment]
done

**Comment by VonSub** [comment]
@xmonader and @Dinaamagdy thx guys!

**Comment by rkhamis** [comment]
Done
