### ISSUE TITLE
Live Capacity Map

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#196]
Show a map with all Capacity on the grid (semi-realtime)

**Comment by despiegk** [comment]
explain what you want to achieve not, clear at all

**Comment by VonSub** [comment]
I would like to feature a map that shows all locations we have capacity up and running at go-live.

**Comment by VonSub** [comment]
Has a cool one bottom of page.
[SONM](https://sonm.com/)

**Comment by VonSub** [comment]
cockpit will do just this.
