### ISSUE TITLE
PARTNER PAGE: check cooperatives on website 

### ISSUE THREAD

**Issue by christopherhutton** [threefoldfoundation/www_threefold.io#198]
according to andreas, we dont have the coop role in our grid ecosystem anymore so i suggest the role is removed from this page

**Comment by despiegk** [comment]
we still have some cooperatives e.g. bettertoken, mazraa and there will be more, I don't think we can remove. Lets revisit the coops in website and see if we need to change something.

**Comment by VonSub** [comment]
They're staying for now I guess? close or put this back into issuelist?
