### ISSUE TITLE
Partnerpage: Remove HPE, FutureCapacity + Link others

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#201]
Remove HPE and Future capacity.
Feature the others a bit bigger 2 x 2

add Links:
https://www.greenedgecloud.com/
https://www.safecity.com/
https://bancadati.farm/
https://www.gigeurope.tech/

**Comment by ehab-hassan** [comment]
(Feature the others a bit bigger 2 x 2) I keep all the same size to make at one line
make 2 x 2 make alot of space
