### ISSUE TITLE
Create Join Us page or Vacancies

### ISSUE THREAD

**Issue by lilianacarrillo** [threefoldfoundation/www_threefold.io#207]
Please add a new page to the website with the open vacancies:
https://docs.google.com/document/d/1iLpdqlBIIGjGmJF2ltg5VAwj8PIhGZXgnMjJqNDiq7M/edit

**Comment by VonSub** [comment]
![artboard](https://user-images.githubusercontent.com/29431263/53333712-eebd3b80-38f6-11e9-9074-5791bb4dce93.png)
![artboard copy](https://user-images.githubusercontent.com/29431263/53333713-eebd3b80-38f6-11e9-9f75-0651e55bbd2a.png)

**Comment by VonSub** [comment]
both are based on roadmap design @ehab-hassan please also add "Jobs" in the menu.

**Comment by samaradel** [comment]
apply now btn should redirect to..?

**Comment by VonSub** [comment]
@samaradel mailto: hiring@threefold.io
