### ISSUE TITLE
Collapse  www_threefold_dynamic_contents into subfolder

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#208]
Please if possible collapse this repo into a subfolder here if possible.
If not possible please clarify why it is not.

https://docs.grid.tf/threefold/www_threefold_dynamic_contents

**Comment by samaradel** [comment]
added [#208](https://github.com/threefoldfoundation/www_threefold.io/commit/c322cf87f45be6193142f81ed1fcb15abd2042c7)
