### ISSUE TITLE
Partnerpage: Add 3 Button underneath HPE

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#214]
We want to feature a 3rd button underneath the HPE section in our partnerpage.
This should be called: 
Hardware

It will link to a wiki. the link will follow.

Style of the button: Blue/White

**Comment by ehab-hassan** [comment]
done, just waiting wiki link or u can update from here
https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/partners/headerpartners.md
hardware_link ="#"

**Comment by VonSub** [comment]
thx @ehab-hassan

**Comment by VonSub** [comment]
link added
