### ISSUE TITLE
No clear "contact us" on the website

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/www_threefold.io#217]
In order to reach to us through email on the website, there is a small line which is difficult to see. I propose making it more clear (bigger size) or maybe adding another block under Social Media saying: 

CONTACT US
Still have questions? Feel free to use the chat you can find in the bottom right of your screen or send us an email on info@threefoldtoken.com

![Screenshot 2019-04-19 at 11 20 02](https://user-images.githubusercontent.com/36316337/56420343-755a1d80-6295-11e9-9a0a-fe0dca4bfe2e.png)

**Comment by VonSub** [comment]
@ehab-hassan can you make this clearer?
