### ISSUE TITLE
Translate intro video into russian

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold.io#220]
We need to translate intro video into russian
https://www.youtube.com/watch?v=4exjbFvnGkk

**Comment by nbabenko** [comment]
Russian voice audio file is ready
@ehab-hassan , can you please share with us also sources of the in-video texts for translation?

**Comment by ehab-hassan** [comment]
[(Script)-Introduction to TFT.docx](https://github.com/threefoldfoundation/www_threefold.io/files/3172392/Script.-Introduction.to.TFT.docx)

that is the original like the one published on youtube

**Comment by nbabenko** [comment]
yes, done, and even more:

https://www.youtube.com/channel/UCaB72EAfckYEyrqRnJEq3hg/videos
