### ISSUE TITLE
Find Solution To Preloader

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#235]
Not a fan of spinner/preloader showing on each page.
We need to find a solution to this asap.
1 load upon initial opening of the page is acceptable, loading on every page, every click... is not.

**Comment by abom** [comment]
Well, the website is not a single web app, we added this loader to hide handlebars.

**Comment by VonSub** [comment]
@abom ok, but how can we fix it. It has to be fixed, one way ore another.

**Comment by ehab-hassan** [comment]
@VonSub the problem that if we remove the loader all text with parsing will appear that why we put the loader give sometimes showing data while it load

**Comment by VonSub** [comment]
i might sound silly, but is it not possible to load it at once and then cache that state? @abom ?

**Comment by abom** [comment]
Everything is possible, but it wasn't build from the start to work like that. If we need it like that, no problem, it would just take more time (cannot give an exact amount until planning what are the changes, but initially, the won't be small).

**Comment by abom** [comment]
We don't do client side rendering, we do server side rendering, then updating it on the client.
