### ISSUE TITLE
Partner page: Decide on cooperative business model

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#24]
https://docs.google.com/document/d/1lWlMJgDLMyjpvS0b1tLqt3HzsVvyQpM8MHa5NkKtsOc/edit?ts=5b868c63#heading=h.j77vkbbja8x8

Solve inconsistencies.

This [model](https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/grid/cost.md) on the Grid page does not match the [business model published here](https://docs.google.com/spreadsheets/d/1vE5A-l5jODhjVog1JkTE4mxZ3EqjiEJOBEC_ayhp-hY/edit?usp=drive_web&ouid=113978207649525299140) in the simulator.

The following are different between the website and the simulator:

Co-op farmers, on the website, seem to be "full service"
Setup fee on site for Co-op Farmer and Individual farmer is 30% v setup of 37% on simulator
Individual Farmer column is the closest model to BT. However, the distribution of tokens does not include 10% to BT as on the simulator.
Cultivation tokens: this appears to be a defined and 'set' message about farmers. But this may not be the case.

**Comment by danleighton** [comment]
OK...I have added a grid to the page trying to lay out the various models.

How we make a sensible description of this I am not sure yet. But I will now have a think about it.

https://docs.google.com/document/d/1lWlMJgDLMyjpvS0b1tLqt3HzsVvyQpM8MHa5NkKtsOc/edit?ts=5b868c63#heading=h.1v1qtn99no76

**Comment by VonSub** [comment]
@andhartl is on it.

**Comment by andhartl** [comment]
content will be moved to the wiki
