### ISSUE TITLE
bring in current roadmap below tech part (see pic)

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold.io#42]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/18591016/44855506-7f2e0280-ac6b-11e8-8372-a980e7ad45a5.png">

**Comment by VonSub** [comment]
current? as in the version we had before?

**Comment by VonSub** [comment]
@ehab-hassan can you put it back, the .MD is in _archive.

**Comment by ehab-hassan** [comment]
done
