### ISSUE TITLE
Technology Page: write content for Blockchain/Zero Chain/TF Chain

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#55]

**Comment by weynandkuijpers** [comment]
First version done here: https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/tech/techbenefit.md

**Comment by weynandkuijpers** [comment]
Suggestion:  change the sequence of the two pages: techbenefits.md first on the tech section and then coretech.md
