### ISSUE TITLE
Team Page: Create content md: Call to action

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#65]
Ask people to get in touch if they would like to become an ambassador

**Comment by VonSub** [comment]
Add CTA section to Teampage @samaradel 
<img width="1064" alt="screen shot 2018-09-03 at 14 28 15" src="https://user-images.githubusercontent.com/29431263/44992700-532abe00-af98-11e8-9771-70d62bdd4d00.png">

**Comment by VonSub** [comment]
when done please link .MD here.

**Comment by samaradel** [comment]
[cta.md](https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/team/cta.md)
