### ISSUE TITLE
Recreate Roadmap using Noia.network style (see below)

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/www_threefold.io#66]
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/18591016/44862294-a9d38780-ac7a-11e8-9107-4f194e1ef587.png">

**Comment by VonSub** [comment]
@ehab-hassan can you look up how to do this? I have found some templates here: 

https://freefrontend.com/css-timelines/#horizontal-timelines

Of course make it fit our Brand Style.
