### ISSUE TITLE
Token page: delete steps 1-3, and move how to onboard to wiki

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#70]
These ones:

https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/tokens/step_1.md

https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/tokens/step_2.md

https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/content/tokens/step_3.md

**Comment by VonSub** [comment]
Steps deleted will see with @yveskerwyn to get them in the Wiki

**Comment by VonSub** [comment]
https://threefoldfoundation.github.io/info_tokens/#/why_buy_tft
