### ISSUE TITLE
Token page: ThreeFold stats & explorers: clarify

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#71]
Decision tree:

A. Do we need two explorers? Why? @nbabenko Please explain why.
B. If no clear benefit > Remove 1.
C. Which one to keep?

Original issue:
_Need to explain Explorer 1&2 difference._

In this doc, it is unclear what the above line means. Clarity needed. An issue can then be raised.

https://docs.google.com/document/d/1lWlMJgDLMyjpvS0b1tLqt3HzsVvyQpM8MHa5NkKtsOc/edit?ts=5b868c63#heading=h.vb4y203auawq

**Comment by danleighton** [comment]
After discussion with Adnan. Changed title of issue to reflect actual problem.

**Comment by VonSub** [comment]
We have multiple explorers because every once in a while they get updated and they do so gradually so we always have one up and running. (we have 4 actually) so we always have 1 that works since the app is linked as well. (check this with the tech guys)

**Comment by VonSub** [comment]
Decide: do we really need to clarify @AdnanFatayerji @danleighton @andhartl @weynandkuijpers
