### ISSUE TITLE
Naming conventions: update across site

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#79]
Adnan, Andreas, Weynand, Dan, Nikolay, Yves (with previous discussions with Jenne and Chris) met to discuss this issue and this represents the consensus view reached on 29 Aug.

This does _not_ imply that all names need to be changed in all the development repos or code. Just the marketing sites and branding, etc.

**Comment by VonSub** [comment]
going to split this up into smaller issues.
