### ISSUE TITLE
Token Page: Multiple naming issues in list.html

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#95]
There appear to be random names for the structure in this file:
https://github.com/threefoldfoundation/www_threefold.io/blob/master/www.threefold.io/themes/landing/layouts/tokens/list.html

Probably needs a review!

**Comment by VonSub** [comment]
needs review, but no prior for 1.0.1. this will be 1.0.3. when everything is really set up.

**Comment by VonSub** [comment]
will make seperate issues for this
